on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    name: pycodestyle
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
          pip install .
      - name: Run tests
        run: pycodestyle --max-line-length=120
  pylint:
    runs-on: ubuntu-latest
    name: pylint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install .
      - name: Run tests
        run: pylint ecpac --rcfile=.pylintrc